### ISSUE TITLE
Example files not working with Python 3.7.0 on Linux

### ISSUE THREAD

**Issue by Delta456** [pvcraven/arcade#366]
## Bug Report
``` python Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyglet/__init__.py", line 351, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'exceptions'

### Actual behavior:
```pythonTraceback (most recent call last):
  File "02_draw_sprites.py", line 4, in <module>
    import arcade
  File "/usr/local/lib/python3.7/site-packages/arcade/__init__.py", line 23, in <module>
    from arcade.application import *
  File "/usr/local/lib/python3.7/site-packages/arcade/application.py", line 8, in <module>
    from arcade.window_commands import set_viewport
  File "/usr/local/lib/python3.7/site-packages/arcade/window_commands.py", line 11, in <module>
    from arcade.monkey_patch_pyglet import *
  File "/usr/local/lib/python3.7/site-packages/arcade/monkey_patch_pyglet.py", line 3, in <module>
    import arcade.sound_wav_monkeypatch as mps
  File "/usr/local/lib/python3.7/site-packages/arcade/sound_wav_monkeypatch.py", line 42, in <module>
    class WAVEFormatException(pyglet.media.exceptions.MediaFormatException):
  File "/usr/local/lib/python3.7/site-packages/pyglet/__init__.py", line 357, in __getattr__
    __import__(import_name)
  File "/usr/local/lib/python3.7/site-packages/pyglet/media/__init__.py", line 144, in <module>
    add_default_media_codecs()
  File "/usr/local/lib/python3.7/site-packages/pyglet/media/codecs/__init__.py", line 141, in add_default_media_codecs
    if have_ffmpeg():
  File "/usr/local/lib/python3.7/site-packages/pyglet/media/codecs/__init__.py", line 157, in have_ffmpeg
    from . import ffmpeg_lib
  File "/usr/local/lib/python3.7/site-packages/pyglet/media/codecs/ffmpeg_lib/__init__.py", line 35, in <module>
    from .libavcodec import *
  File "/usr/local/lib/python3.7/site-packages/pyglet/media/codecs/ffmpeg_lib/libavcodec.py", line 360, in <module>
    avcodec.av_packet_free.argtypes = [POINTER(POINTER(AVPacket))]
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56: undefined symbol: av_packet_free```

### Expected behavior:
Work correctly without any errors
### Steps to reproduce/example code:
Download Python 3.7.0 and pip install arcade.
Download the example folder.
Run the any example using `python` or `python3 filename.py`.

**Comment by Delta456** [comment]
Closing this issue

**Comment by pvcraven** [comment]
Duplicate of #350, ffmpeg not importing on Linux
