### ISSUE TITLE
update to 2.0.1 from 1.3.7: AttributeError: 'NoneType' object has no attribute 'setView_'

### ISSUE THREAD

**Issue by ReblochonMasque** [pvcraven/arcade#336]
## Bug Report
After update to 2.0.1 from 1.3.7, sample programs throw
AttributeError: 'NoneType' object has no attribute 'setView_'
### Actual behavior:
AttributeError: 'NoneType' object has no attribute 'setView_'

Full trace:  

`FFmpeg binaries could not be loaded.`

```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-1998cc790a9a> in <module>
     76 
     77 if __name__ == "__main__":
---> 78     main()

<ipython-input-1-1998cc790a9a> in main()
     71 
     72 def main():
---> 73     window = MyGame(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
     74     arcade.run()
     75 

<ipython-input-1-1998cc790a9a> in __init__(self, width, height, title)
     33 
     34         # Call the parent class's init function
---> 35         super().__init__(width, height, title)
     36 
     37         # Make the mouse disappear when it is over the window.

~/anaconda3/envs/py37/lib/python3.7/site-packages/arcade/application.py in __init__(self, width, height, title, fullscreen, resizable, update_rate, antialiasing)
     51 
     52         super().__init__(width=width, height=height, caption=title,
---> 53                          resizable=resizable, config=config)
     54 
     55         if antialiasing:

~/anaconda3/envs/py37/lib/python3.7/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    641         from pyglet import app
    642         app.windows.add(self)
--> 643         self._create()
    644 
    645         self.switch_to()

~/anaconda3/envs/py37/lib/python3.7/site-packages/arcade/monkey_patch_pyglet.py in _create(self)
     79         # Create a canvas with the view as its drawable and attach context to it.
     80         self.canvas = CocoaCanvas(self.display, self.screen, self._nsview)
---> 81         self.context.attach(self.canvas)
     82 
     83         # Configure the window.

~/anaconda3/envs/py37/lib/python3.7/site-packages/pyglet/gl/cocoa.py in attach(self, canvas)
    287         # The NSView instance should be attached to a nondeferred window before calling
    288         # setView, otherwise you get an "invalid drawable" message.
--> 289         self._nscontext.setView_(canvas.nsview)
    290         self._nscontext.view().setWantsBestResolutionOpenGLSurface_(1)
    291         self.set_current()

AttributeError: 'NoneType' object has no attribute 'setView_'```


### Expected behavior:
No error
### Steps to reproduce/example code:
All example code

**Comment by tarkadaal** [comment]
I'm having the same issue, on Mac OSX 10.14.3. Looks like it's a failing call to NSOpenGLContext.alloc().initWithFormat_shareContext_() in gl/cocoa.py.

**Comment by ReblochonMasque** [comment]
Thank you - you mean 2.0.0 seems to work where 2.0.1 doesn't?

**Comment by pvcraven** [comment]
Version 2.0.0 works, 2.01 fails.

**Comment by pvcraven** [comment]
Can you try 2.0.2b2 version? See if the fix works for you?

**Comment by yuezhuuuu** [comment]
Hi, I have the same issue, but where can I download the 2.0.0 version

**Comment by ReblochonMasque** [comment]
@yuezhuuuu , you can `pip install arcade==2.0.0`

**Comment by ReblochonMasque** [comment]
@pvcraven 2.0.2b2 seems to work, thank you.  
It still throws a `FFmpeg binaries could not be loaded.` where 1.3.7 did not - I dunno why. You have any ideas?
